name: Jest Example
on: push
jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: env
    - run: npm install
    - name: Run Tests
      uses: ./.github/action
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
